'use client'

import './globals.css'
// import { Inter } from 'next/font/google'
import { ThemeProvider, useTheme } from 'next-themes';
import { Navbar } from '@/components/ui/Navbar'


// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='black'>
      <head />
      <body >
        <ThemeProvider enableSystem={true} attribute='class'>
          <Navbar />
          {children}  
        </ThemeProvider>       
      </body>
    </html>
  )
}
